### ISSUE TITLE
ipad游玩谱面问题

### ISSUE THREAD

**Issue by hina-cyt3663** [ReiKohaku/BanG-Player-v2#1]
ios 13.6
Ipad 2019 safari和chrome均有问题
点击游玩谱面，下载完成后显示null is not an object（this什么creatchain）

**Comment by ReiKohaku** [comment]
问题已定位并修复。
问题原因：点击音效创建的AudioContext对象过多，导致不能新建AudioContext对象。
问题修复：将AudioContext存储到变量内供点击音效使用。
感谢您的反馈。
